
---
title: "گزارش فاز دوم پروژه تحلیل داده موسیقی"
author: "نگار مخبریان - مهدی بهروزی خواه"
output: html_document
---
<html dir="rtl"><meta charset="UTF-8" />
<font face="XB Niloofar">
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## دادهها
در این فاز ما ابتدا به جستوجوی داده پرداختیم. دادههای زیادی بر اینترنت در رابطه با موسیقی قرار دارند.
در واقع چند سایت اصلی و کلیدی وجود دارند که ما با آنها آشنا شدیم. اولی سایت lastfm است که کاربران آهنگهایی که گوش میدهند را با استفاده از  api های نوشته شده در سایت ثبت میکنند. در نتیجه آرشیو بسیار بزرگی از آهنگها و آدمهایی که آن آهنگها را گوش داده اند دارد.
اما دریافت این اطلاعات نیازمند query زدن به سایت است. ما سعی کردیم ابتدا فرآیند را انجام دهیم و با استفاده از پایتون میتوانیم اطلاعات هر کاربری را کامل دریافت کنیم. البته این سایت اطلاعات بسیار بیشتری میدهد که در ادامه به توضیح آن میپردازیم اما مشکل آن این است که نمیشود برای کار train استفاده کرد زیرا با هر پرسمان اطلاعات کمی را میدهد.
با چستجوی بیشتر توانستیم آرشیو خوبی دادههای این سایت پیدا کنیم. که با آنها کار کنیم.

سایت مهم دیگری که پیدا کردیم سایت  musicbrainz بود که در واقع هدفشان جمع آوری آرشیو کل دادههای موسیقی بود برای کارهای تحلیلی.
این سایت اطلاعات بسیار خوبی دارد و کل پایگاه داده اشان را به رایگان چهت دانلود گذاشته اند که ما از آن نیز استفاده کردیم.
برای مثال کار جالبی که این سایت کرده این است که برای هر آهنگ یک آیدی مشخص درآورده در نتیجه آهنگها با هم قاطی نمیشوند.

سایت آخری که دادهها را از آن برداشتیم، به اسم پروژه  one milion songs معروف است. این دادهها، اطلاعات ۱ میلیون آهنگ است که همه چیز آنها را از سایت های مختلف و معروف جهان جمع کردهاند و کنار هم قرار دادهاند تا کارهای تحلیلی بهتری روی دادههای موسیقی انجام شود.
در این پروژه ما از این دادهها نیز استفاده کردیم.

برای اینکه در این فاز منابع ما مختلف بود و حجم دادهها بسیار بالا بود، بیشتر تمرکزمان روی جمع آوری دادهها بود.

## تمیز سازی داده
از جمله کارهای مهمی که در این فاز کردیم، تمیز سازی داده بود. همانطور که گفته شد دادهها از منابع مختلف بودند. سعی کردیم همه را به شکل پایگاه دادهای در قالب sqlite در بیاوریم و دادهها را از آن بخوانیم و در آن بنویسیم تا هم از کارهای تکراری جلوگیری شود هم مدیریت ram و سرعت پردازش بیشتر شود. در مجموع حجم داده ها به بیش از ۲۰ گیگ رسید.

## برخی تحلیلهای صورت گرفته
تحلیل های مختلفی در این فاز انجام شد. که بعضی از آنها به نتیجه رسید و برخی دیگر خیر.
برای مثال سعی کردیم ماتریس sparse آهنگها بر حسب تگ را بسازیم. و چون تعداد تگها بسیار بالا بود، ایده ای به ذهنمان رسید که با استفاده از pca میتوانیم دادهها را خلاصه کنیم و تگها را از یک ماتریس چند هزارتایی به یک ماتریس ۱۵۰ تایی تبدیل کردیم که حدود ۷۰ درصد واریانس دادهها را شامل میشد. به این طریق در آینده بردار خوبی از هر آهنگ داریم. برای اینکار چون دادهها زیاد بودند، سعی کردیم روی ۳۰ درصد دادهها train کنیم.

کار دیگری که کردیم بررسی کلی آهنگها و تعداد شنودهها با توجه به تگ و تعداد پخش آنها بود. برای مثال سعی کردیم تا طول آهنگ را با توجه به سبک آهنگ  و خواننده و تعداد پخش تخمین بزنیم که چیز جالبی نشد.

